name: GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
        working-directory: docs/react-portfolio
      - name: Build React app
        run: npm run build
        working-directory: docs/react-portfolio
      - name: Copy project pages into docs
        run: |
          mkdir -p docs/projects
          cp -r projects/* docs/projects/
          find docs/projects -name 'index.md' -exec sed -i 's|../../docs/assets/css/style.css|../assets/css/style.css|g' {} +
      - uses: actions/configure-pages@v5
      - uses: actions/upload-pages-artifact@v3
        with:
          path: docs
      - uses: actions/deploy-pages@v4
